### ISSUE TITLE
Can you compile your project in STM32CubeIDE 1.10.1?

### ISSUE THREAD

**Issue by P55-rgb** [rbalykov/bluepill-midi#1]

**Comment by rbalykov** [comment]
Maybe, but what for? You can use compiled binaries in Releases or just `make` it on any linux machine

**Comment by P55-rgb** [comment]
I program on Windows.
STM32CubeIDE 1.10.1 does not create a standard Midi USB project and I do not know how to create it: (
If you are from Russia, then write in Russian:)

**Comment by rbalykov** [comment]
Cube/CubeMX никогда не предлагали шаблон usb-midi-class, IDE видимо тоже (его целая проблема скачать, санкции).
Дескриптор (сложно-составной, с несколькими эндпойнтами) USB-Midi можно сгенерировать через Cypress PSoC creator, бесплатную версию. 

А можно сделать форк данного проекта, в нем уже шесть эндпойнтов, 3in+3out, поменять обработчики и все.

**Comment by P55-rgb** [comment]
Чтобы скачать Cube IDE достаточно включить любой VPN (я качаю без проблем).
Надо будет попробовать сгенерировать дескриптор.

Нашел в сети вот этот проект (изм. расширение на 7z).
Он собирается, в диспетчере устройств появляется устройство, но оно перехватывает звук когда его включаешь (похоже как динамик определяется, а не как миди usb).
[USB_COM_port.zip](https://github.com/rbalykov/bluepill-midi/files/9297499/USB_COM_port.zip)

**Comment by rbalykov** [comment]
Выбор тот же, что и в КубеМХ - Audio Device Class, звуковая карта.
Ответ получился выше: форк данного проекта и допиливание.

**Comment by P55-rgb** [comment]
А какой файл качать?

![image](https://user-images.githubusercontent.com/63473590/183842196-d4bd1386-1f2f-40f5-b1aa-d8f8415a79cf.png)

**Comment by rbalykov** [comment]
наверное последний
